# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20160524_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
