# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20160525_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='current_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
