# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_current_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('pdf', 'Pdf Book'), ('net', 'Online Book'), ('vid', 'Video Tutorial'), ('con', 'Video of conference')], default='pdf', max_length=3),
            preserve_default=False,
        ),
    ]
