# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20170603_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
